### ISSUE TITLE
Use upstream DallasTemperature lib instead of fork

### ISSUE THREAD

**Issue by pstolarz** [SensESP/OneWire#2]
You need no more to use my fork of DallasTemperature in the PlatformIO env. The better way is to use upstream library:
So replace
```
lib_deps =
   SignalK/SensESP@^2.0.0
   pstolarz/OneWireNg@^0.10.0
   https://github.com/pstolarz/Arduino-Temperature-Control-Library
```
by
```
lib_deps =
   SignalK/SensESP@^2.0.0
   pstolarz/OneWireNg@^0.10.0
   DallasTemperature@^3.9.1
lib_ignore =
   OneWire
```
and everything should be fine. I don't promise I'll maintaing my DallasTemperature fork up to date.

**Comment by mairas** [comment]
Thanks for the heads-up. I can definitely relate why this is the way to go.

I think we might have a minor issue here, though: I can't find any equivalent of `lib_ignore` in the `library.json` syntax. This repo would normally be used as a library, so `platformio.ini` would be always ignored and `library.json` used instead. 

So, I think the correct solution would be to give up using `milesburton/DallasTemperature` and the `OneWire` compatibility interface, and instead go all the way with `OneWireNg` and use the provided `DSTherm` driver.

**Comment by pstolarz** [comment]
> So, I think the correct solution would be to give up using milesburton/DallasTemperature and the OneWire compatibility interface, and instead go all the way with OneWireNg and use the provided DSTherm driver.

Definitely it'd be the best solution. In my free time I'd be happy to provide PR to this project with this change.

**Comment by mairas** [comment]
Ooh, that'd be awesome!

**Comment by pstolarz** [comment]
Since this issue is no more relevant I'm closing it.
